-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 00:07:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculos` (
  `codcar` INT NOT NULL,
  `placa` VARCHAR(9) NOT NULL,
  `descr` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`codcar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bomba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bomba` (
  `nbomb` INT NOT NULL,
  `capac` INT NULL,
  PRIMARY KEY (`nbomb`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionarios` (
  `codfun` INT NOT NULL,
  `nomfun` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`codfun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Abastecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Abastecimento` (
  `Bomba_nbomb` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `litros` INT NULL,
  `KM` INT NULL,
  `codcar` INT NOT NULL,
  `Funcionarios_codfun` INT NOT NULL,
  PRIMARY KEY (`Bomba_nbomb`, `data`, `hora`),
  INDEX `fk_Abastecimento_Bomba_idx` (`Bomba_nbomb` ASC) VISIBLE,
  INDEX `fk_Abastecimento_Veiculos1_idx` (`codcar` ASC) VISIBLE,
  INDEX `fk_Abastecimento_Funcionarios1_idx` (`Funcionarios_codfun` ASC) VISIBLE,
  CONSTRAINT `fk_Abastecimento_Bomba`
    FOREIGN KEY (`Bomba_nbomb`)
    REFERENCES `mydb`.`Bomba` (`nbomb`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Abastecimento_Veiculos1`
    FOREIGN KEY (`codcar`)
    REFERENCES `mydb`.`Veiculos` (`codcar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Abastecimento_Funcionarios1`
    FOREIGN KEY (`Funcionarios_codfun`)
    REFERENCES `mydb`.`Funcionarios` (`codfun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
