-- MySQL Script generated by MySQL Workbench
-- Thu Nov 10 23:07:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplinas` (
  `coddis` INT NOT NULL,
  `nomedis` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`coddis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turmas` (
  `codTurmas` INT NOT NULL,
  `semlet` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`codTurmas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professores` (
  `codProf` INT NOT NULL,
  `nomeProf` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`codProf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Horarios` (
  `codhor` TIME NOT NULL,
  `diasem` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `haula` TIME NOT NULL,
  `sala` INT NOT NULL,
  `coddis` INT NOT NULL,
  `codTurmas` INT NOT NULL,
  `codProf` INT NOT NULL,
  PRIMARY KEY (`codhor`),
  INDEX `fk_Horarios_Disciplinas1_idx` (`coddis` ASC) VISIBLE,
  INDEX `fk_Horarios_Turmas1_idx` (`codTurmas` ASC) VISIBLE,
  INDEX `fk_Horarios_Professores1_idx` (`codProf` ASC) VISIBLE,
  CONSTRAINT `fk_Horarios_Disciplinas1`
    FOREIGN KEY (`coddis`)
    REFERENCES `mydb`.`Disciplinas` (`coddis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horarios_Turmas1`
    FOREIGN KEY (`codTurmas`)
    REFERENCES `mydb`.`Turmas` (`codTurmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horarios_Professores1`
    FOREIGN KEY (`codProf`)
    REFERENCES `mydb`.`Professores` (`codProf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alunos` (
  `codAlu` INT NOT NULL,
  `nomeAlu` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`codAlu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Det_Horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Det_Horarios` (
  `codhor` TIME NOT NULL,
  `codAlu` INT NOT NULL,
  PRIMARY KEY (`codhor`, `codAlu`),
  INDEX `fk_Horarios_has_Alunos_Alunos1_idx` (`codAlu` ASC) VISIBLE,
  INDEX `fk_Horarios_has_Alunos_Horarios_idx` (`codhor` ASC) VISIBLE,
  CONSTRAINT `fk_Horarios_has_Alunos_Horarios`
    FOREIGN KEY (`codhor`)
    REFERENCES `mydb`.`Horarios` (`codhor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horarios_has_Alunos_Alunos1`
    FOREIGN KEY (`codAlu`)
    REFERENCES `mydb`.`Alunos` (`codAlu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
