-- MySQL Script generated by MySQL Workbench
-- Fri Nov 11 17:43:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pacientes` (
  `codpac` INT NOT NULL,
  `nompac` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`codpac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Convenios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Convenios` (
  `codconv` INT NOT NULL,
  `nomeconv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codconv`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Quartos` (
  `codQuarto` INT NOT NULL,
  `numQuarto` INT NOT NULL,
  PRIMARY KEY (`codQuarto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exames` (
  `codExames` INT NOT NULL,
  `nomExame` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`codExames`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicos` (
  `codMedico` INT NOT NULL,
  `nomeMedico` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`codMedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Setores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Setores` (
  `codSetor` INT NOT NULL,
  `nomeSetor` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`codSetor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fichas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fichas` (
  `fichanum` INT NOT NULL,
  `codpac` INT NOT NULL,
  `dt_baixa` DATE NOT NULL,
  `codQuarto` INT NOT NULL,
  `codMedico` INT NOT NULL,
  `codSetor` INT NOT NULL,
  PRIMARY KEY (`fichanum`),
  INDEX `fk_Fichas_Medicos1_idx` (`codMedico` ASC) VISIBLE,
  INDEX `fk_Fichas_Setores1_idx` (`codSetor` ASC) VISIBLE,
  INDEX `fk_Fichas_Quartos1_idx` (`codQuarto` ASC) VISIBLE,
  INDEX `fk_Fichas_Pacientes1_idx` (`codpac` ASC) VISIBLE,
  CONSTRAINT `fk_Fichas_Medicos1`
    FOREIGN KEY (`codMedico`)
    REFERENCES `mydb`.`Medicos` (`codMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fichas_Setores1`
    FOREIGN KEY (`codSetor`)
    REFERENCES `mydb`.`Setores` (`codSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fichas_Quartos1`
    FOREIGN KEY (`codQuarto`)
    REFERENCES `mydb`.`Quartos` (`codQuarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fichas_Pacientes1`
    FOREIGN KEY (`codpac`)
    REFERENCES `mydb`.`Pacientes` (`codpac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fichas_has_Convenios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fichas_has_Convenios` (
  `fichanum` INT NOT NULL,
  `Convenios_codconv` INT NOT NULL,
  PRIMARY KEY (`fichanum`, `Convenios_codconv`),
  INDEX `fk_Fichas_has_Convenios_Convenios1_idx` (`Convenios_codconv` ASC) VISIBLE,
  INDEX `fk_Fichas_has_Convenios_Fichas_idx` (`fichanum` ASC) VISIBLE,
  CONSTRAINT `fk_Fichas_has_Convenios_Fichas`
    FOREIGN KEY (`fichanum`)
    REFERENCES `mydb`.`Fichas` (`fichanum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fichas_has_Convenios_Convenios1`
    FOREIGN KEY (`Convenios_codconv`)
    REFERENCES `mydb`.`Convenios` (`codconv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fichas_has_Exames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fichas_has_Exames` (
  `fichanum` INT NOT NULL,
  `codExames` INT NOT NULL,
  PRIMARY KEY (`fichanum`, `codExames`),
  INDEX `fk_Fichas_has_Exames_Exames1_idx` (`codExames` ASC) VISIBLE,
  INDEX `fk_Fichas_has_Exames_Fichas1_idx` (`fichanum` ASC) VISIBLE,
  CONSTRAINT `fk_Fichas_has_Exames_Fichas1`
    FOREIGN KEY (`fichanum`)
    REFERENCES `mydb`.`Fichas` (`fichanum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fichas_has_Exames_Exames1`
    FOREIGN KEY (`codExames`)
    REFERENCES `mydb`.`Exames` (`codExames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
